### ISSUE TITLE
On naming

### ISSUE THREAD

**Issue by ghost** [doherty/App-Sysadmin-Log-Simple#14]
I just saw GumbyPAN announce a new upload of this, and immediately I was a bit baffled by your choice of name. 'App::Sysadmin' doesn't really communicate anything. It's rather generic and has little meaning on its own. Perhaps drop the Sysadmin bit?

Additionally, placing a program called 'log' in bin/ is not the best idea. You may clobber an existing system tool (thankfully you didn't choose logger which definitely does exist). I know you're going for short and concise, but you must also take care not to collide with existing system utilities. If you'd like, we can talk about naming stuff a bit at YAPC.

**Comment by doherty** [comment]
I won't be at YAPC this year or next - but I certainly agree with you about the name. However, I'm not sure `App::Log(::Simple)` is any better. Saying `Syslog` is worse, implying that it talks to syslog. Maybe `SystemLog`? But of course, you could log anything you want with it, not just sysadmin notes.

On the executable - I checked on my own systems for a 'log' command. I should probably add a note that this isn't really meant for others to use yet, and also choose a different name for it...

I'll think more on this later.
